### ISSUE TITLE
not working on Sense June 2018

### ISSUE THREAD

**Issue by imtiazu** [HighCoordination/trueChart-Menubar4Sense#15]
![image](https://user-images.githubusercontent.com/11614992/43138301-50dabf0a-8f46-11e8-93cb-220d2d34e85e.png)

**Comment by HighCoordination** [comment]
please download the latest version of tcMenu from https://www.highcoordination.com/downloads/truechart-menubar/

**Comment by imtiazu** [comment]
Thanks – it works. Do you have a demo qvf please? I’m trying to toggle full screen without luck. Thanks

**Comment by HighCoordination** [comment]
Hey!

There is currently no tcMenubar _only_ demo App available.
Regarding your request, it seems like you had an older version and there was a bug for toggling fullscreen mode.
This is fixed in the latest release.
Hopefully this screenshot will help you to create an toggle

[cid:image002.jpg@01D42367.7A295600]

Best Regards,
Uwe Rominger

Von: imtiazu <notifications@github.com>
Gesendet: Dienstag, 24. Juli 2018 15:41
An: HighCoordination/trueChart-Menubar4Sense <trueChart-Menubar4Sense@noreply.github.com>
Cc: software <software@highcoordination.de>; State change <state_change@noreply.github.com>
Betreff: Re: [HighCoordination/trueChart-Menubar4Sense] not working on Sense June 2018 (#15)

Thanks – it works. Do you have a demo qvf please? I’m trying to toggle full screen without luck. Thanks

**Comment by imtiazu** [comment]
Thanks, working now.
One thing however – I’m trying to dynamically change the color of the button background when selected.
Do you know what the variable is for the toggle action so that I can use it conditionally?

Eg If (toggleon = 1…) ?
Thanks

**Comment by HighCoordination** [comment]
There is variable for toggle… BUT!

You could do it the other way round.
Create a variable and bind the fullscreen toggle on that variable (and your background color)
And instead of toggling fullscreen / normal you just change the value of your variable from 0 <-> 1.

Best Regards,
Uwe

Von: imtiazu <notifications@github.com>
Gesendet: Dienstag, 24. Juli 2018 16:07
An: HighCoordination/trueChart-Menubar4Sense <trueChart-Menubar4Sense@noreply.github.com>
Cc: software <software@highcoordination.de>; State change <state_change@noreply.github.com>
Betreff: Re: [HighCoordination/trueChart-Menubar4Sense] not working on Sense June 2018 (#15)

Thanks, working now.
One thing however – I’m trying to dynamically change the color of the button background when selected.
Do you know what the variable is for the toggle action so that I can use it conditionally?

Eg If (toggleon = 1…) ?
Thanks

**Comment by imtiazu** [comment]
Thanks, how would I bind that?
