### ISSUE TITLE
Variable dropdown select doesn't redraw

### ISSUE THREAD

**Issue by Kielland** [HighCoordination/trueChart-Menubar4Sense#2]
Hi

You guys have created an amazing extension that brings a lot of value! I do have a couple of inputs:

1) In the variable dropdown, if the user selects a dropdown button, the variable value will change, but the dropdown will not reflect that the new variable is selected. (Workaround is to use a selection label. When this changes, i guess the control is re-drawn.)

2) When variable is selected, normal dropdown behaviour would be to close the dropdown. I recommend this, as it feels smoother than having to click the dropdown header.

3) Would it be possible to add a property to customize the height of variable dropdown elements? This is just a nice to have.

4) A killer functionality would be to hide most of the menubar when it's not used. Just keep a header. When the user clicks the header, the full menubar slides out (above other dashboard elements). It would be great to save some real estate.

5) To use the selection controls in the menubar, the user currently has to add dimensions into the dimensions section first. The great thing about TrueChartMenubar is that you could add all selection possibilities into the control, because it's hierarchically structured. However, Qlik gets quickly into memory trouble if you add a lot of dimensions into the same control. (I guess it builds a memory cube with all the added dimensions. This is OK for normal controls, where the point is to calculate values for all intersections between dimension values. But in TrueChartMenubar, the purpose is just to provide the ability to filter by many dimensions using the same extension. Hence, it's be better, if it's possible, to let the user add the dimensions directly into the sense select items using expression fields.

Thanks again!

**Comment by HighCoordination** [comment]
@Kielland Thank you for your good ideas and hints. I will try to answer briefly here....

Regarding your points:

**1. Variable dropdown not reflect selected value**
Unfortunately, I can't reproduce your problem. As you can see in our demo, another variable value is correctly highlighted in the sub-elements (Demo-Link: https://sense.highcoordination.de/demo/extensions/HiCoDemo/HiCoDemo.html#app=trueChartDemo&page=1)
While I'm writing this, I notice that you might think that the variable dropdown in the default state does not output the variable value as a selection label? This is indeed deliberate as we wanted to avoid unintentionally displaying technical variables values. In this respect, only a manually defined selection label really helps.

I will include a feature request to customize this default behavior (HICO-40795).

**2. Close selection element (variable dropdown) after click**
We still this feature on our roadmap and it's currently planned for version v1.6 (HICO-2565).

**3. Option to customize the height of dropdown elements**
I will create a feature request for version v3.0 (HICO-40800)

**4.  Side bar option**
It's possible...We still this feature on our roadmap and it's currently planned for version v2.0 (HICO-40536).

**5. Perfomance due to many fields**
Thank you for your great analysis of this problem. Indeed, we have already become aware of this problem. We have planned the revision of the field dimensions for version v1.5 (HICO-40739). There we will extend the use of the Hypercubes and only use the child objects, this is exactly the same approach as with the Sense Filter Panel.

Best regards
Stefab

**Comment by Kielland** [comment]
Great! I look forward to all that - especially v1.5 with the ability to add many dimensions from different tables without choking the server memory.

Regarding section 1: You write "I notice that you might think that the variable dropdown in the default state does not output the variable value as a selection label?"

No, this was not what I meant. I understand that you don't want to display the variable value. Using a manually defined selection label is absolutely fine. (Hence, I would not prioritize feature request '40795' if I were you.)

What I did mean was this: In the variable dropdown, the selected element is highlighted. However, it is not correctly highlighted when you click a new element to change the variable value. If you use a selection label, this problem goes away, which is probably why you couldn't reproduce the problem.

If you still cannot reproduce the error, never mind. Perhaps there is something particular about my environment.

Thanks again!
Tor
